production:
  adapter: postgresql
  encoding: unicode
  database: imagine_cms_dev
  pool: 5
  username:
  password:
development:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username:
  password:
