production:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username:
  password:
development:
  adapter: postgresql
  encoding: unicode
  database: imagine_cms_dev
  pool: 5
  username: imagine_csm
  password: imabeer91
test:
  adapter: postgresql
  encoding: unicode
  database: imagine_cms_test
  pool: 5
  username: imagine_cms
  password: imabeer91
